# Site
name: "Mafiakitty"
title: "Mafiakitty Sailing"
description: "Mafiakitty Adventures"
meta_description: "Mafiakitty is sailing, living off grid, and elimating bills."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: '/'
email: 'mikennedy@gmail.com'
google_analytics: ''
disqus: 'demowebsite'
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  mike:
    name: Mike
    display_name: Mike
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: 
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Affiliates, a template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  michelle:
    name: Michelle
    display_name: Michelle
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: 
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  #permalinks:
    #category: '/:categories/:name/'
    
permalink: /:year/:month/:day/:title:output_ext

# Other
markdown: kramdown
highlighter: rouge
